<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="0.19.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodexSharp.Protocol\CodexSharp.Protocol.fsproj" />
    <ProjectReference Include="..\CodexSharp.Core\CodexSharp.Core.fsproj" />
  </ItemGroup>
</Project>
